name: Build and deploy ASP.NET WebForms App - aroup-onlineshopping

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore NuGet packages
        run: nuget restore OnlineShopping.sln

      - name: Build and publish WebForms project
        run: |
          msbuild "Lesson-10(DataTable_Edit_DeleteData)/Lesson-10(DataTable_Edit_DeleteData).csproj" `
            /p:DeployOnBuild=true `
            /p:WebProjectOutputDir="$(Build.ArtifactStagingDirectory)\WebApp" `
            /p:OutputPath="$(Build.ArtifactStagingDirectory)\WebApp" `
            /p:Configuration=Release `
            /p:PackageAsSingleFile=false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webforms-app
          path: ./Lesson-10(DataTable_Edit_DeleteData)/bin/Release/

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webforms-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aroup-onlineshopping'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E2EEC27938A446E7A62D9D28F40F3933 }}
          package: .
